### PR TITLE
Adding Pawns

### LINKED ISSUE #20: Feature: Add pawns
Pawns always start on the 2nd row and move and take like standard pawns. If they reach the top row, they get promoted to queens!

### PR DESCRIPTION
**Pull request by cethemaco**
Resolves #20.

So, this is my attempt at adding pawns to the game.

Since unlike every other piece, which attacks and moves to the same squares, pawns only attack diagonals and move fowards, my idea was to first generate the moves in either direction, and then throw out the moves that would go to the opposite direction.
Also, this behaviour required me to add a bunch of special cases to any thing related to pawn placements.

After rigorous testing, I can confirm that it _should_ not break anything.
However, the lightblue squares that represent the squares threatened by the pawns are a bit unintuitve: It only draws the diagonals if the white Knight is actually occupying them, otherwise they don't get drawn.
This is because this move is only considered possible when the white knight is actally threathened.

### CODE REVIEW

**Comment by acenturyandabit** [comment]
Hey, I love these pawns! The arrows are perfect :) Also I'm happy with the behaviour of the blue squares :D

In fact, I would up their spawn rate a bit (spawntries 3>4), since I rarely seem to see them...

... but when I do, whoa they promote really quickly! Can we make it so they only move every 2 turns? So you have 10 turns to stomp them instead of just 5?

**Comment by cethemaco** [comment]
So here is a quick implementation of that, however, one question arised: Right now, pawns also take every second turn. Should that change?

**Comment by acenturyandabit** [comment]
Hey, i think either:
- indicate _when_ the pawns are going to move/take visually, or
- let the pawns always take, on every move

Also if you want to clean up your git history, you can perform an interactive rebase against master:
`git rebase -i master`
https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase
You will need to `git push --force` to your PR later, that is normal for a rebase :)

Thanks for the work!

**Comment by cethemaco** [comment]
Okay, so I went with the second option and made it so that pawns take on every turn. I have adjusted the index.html file to adjust for that change.
Also, thanks for the tip with `git rebase -i master`, this really helped cleaning up the mess I made earlier! (Although this is only reflected in the general commit history and not here in the pull request)

**Comment by acenturyandabit** [comment]
Approved, thank you!

**Pull request merged**
