### PR TITLE
refactor: remove repetition

### LINKED ISSUE #86: Refactor to remove repetition
There's some repetition of  tags in the code for the green move indicators. This along with other repetitions can be omitted by generating the img tags in javascript.

### PR DESCRIPTION
**Pull request by VelialCypher**
Added generation of player movement points

Simplified drawPlayerPossibleMoves function

Added a couple of helper functions:
playerCanMove
coordsTo2D
coordsTo1D

Fix #86

### CODE REVIEW

**Comment by acenturyandabit** [comment]
Hey,  great work! You cleaned up a lot :)

A few quick asks while you're here: Could you...

1. Create a new `movement_hints.js` file and extract the movement hint code from `main.js / dark_mode.js` [separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns)
2. Reuse your utility function in another place: in `document.querySelector('.board').addEventListener('click',` there is an if-statement that decides whether the knight is allowed to move to a square. (Note there's an extra move available to the knight that is not highlighted: staying on its own square.)

Thanks again for the help!

**Comment by VelialCypher** [comment]
Thank you!
No problem, I'll do it :)

I was planning to reuse the logic, but decided not to be scatterbrained and solve the main problem first.

As for the first point, I didn’t quite understand - but I’ll try to figure it out, in which case I’ll ask clarifying questions.

**Comment by VelialCypher** [comment]
I'll clarify on the first point :)

Extract highlighting movements only player (green dots, red squares)?

**Comment by acenturyandabit** [comment]
Yeah sure, can make it player_movement_hints.js :)

**Comment by VelialCypher** [comment]
I did.

The second, I think, is well done.

With the first one, it probably didn’t work out quite correctly, in any case - I will be glad for any ideas if you need to correct or rewrite :)

**Comment by acenturyandabit** [comment]
Fantastic! I'm glad you moved everything into a function for OOP :)

Merging now, thank you so much!

**Pull request merged**
