### PR TITLE
Added multi-kill achievements

### LINKED ISSUE #89: Achievement: Multi-Kills
I think having achievements that pop up whenever you kill multiple pieces in a row, would be a very great and natural addition

### PR DESCRIPTION
**Pull request by cethemaco**
Resolves #89.

My attempt at adding Multi-Kill achievements.

Basically, I created a combo variable that counts up when ever a kill has happened and if no kill happened, then it resests back to 0.

### CODE REVIEW

**Comment by acenturyandabit** [comment]
Will check this out soon, thanks :)

**Comment by acenturyandabit** [comment]
Hey, nice work! 

There's a tiny bug where combo doesn't reset when games are reset - can you pop a `combo=0` into `resetGame()`?

**Comment by cethemaco** [comment]
Oh, I missed that, fixed that!

**Comment by acenturyandabit** [comment]
Neat, thank you!

**Pull request merged**
