### PR TITLE
Add new game mode loop pieces

### PR DESCRIPTION
**Pull request by ZetsuBk**
hello

I add new game mode loop pieces.

### CODE REVIEW

**Comment by acenturyandabit** [comment]
Hi, That's a very creative game mode! I saw you added the blue squares but also removed them, which is great :)

A little feedback: 
- I'd suggest rotating the pieces first before they move - many times I have pieces which would rotate but move out of the edge first, so they don't rotate. 
- Perhaps instead of calling the game mode "loop pieces", you could call it "tornado mode?" Loop pieces sounds like the pieces can go through the edge of the board.
- Some of the game modes have custom instructions at the bottom - you can get your game mode to add a custom instruction that tells users what to expect.

If you're tight on time then I don't mind merging straight away, and leaving the issues I mentioned above as bugs for future developers to work on - just leave a comment :)

Thanks again for your contribution!

**Comment by ZetsuBk** [comment]
Hi, Thanks for the feadback :)

I like the new name "Tornado mode" I will add it and the instruction. 
For the first suggest I will leave it for future developers to work on.

**Comment by ZetsuBk** [comment]
I had probleme  with branch update so i add files via upload

**Comment by HackerFrosch** [comment]
> I had probleme with branch update so i add files via upload

Not a good thing, because it will replace all other changes made in other files. Would be nice if you made another pr wich only adds your changes.

**Comment by HackerFrosch** [comment]
Gonna close this pr and make a new one

**Pull request closed without merging**
